### PR TITLE
Fix DslMarker annotations.

### LINKED ISSUE #125: Wrong @DslMarker annotations
Hi guys!
I have some problem

Right now i can write something like that
```
cardsRecyclerView {
    cardsRecyclerView {
        cardsRecyclerView {
            hasDescendant {
                hasDescendant {
                    hasDescendant {  }
                }
            }
        }
    }
}
```
This code is totally wrong
The construction does not make sense (the list in the same list in the same list checks something there and 2 more levels of checks). This is impossible to create in a real ui

This is because the kakao dsl used different `@DskMarker` annotations
I think you should choose one marker annotation for all dsl and the problem will gone

### PR DESCRIPTION
**Pull request by Unlimity**
Fixes #125 
Also update docs to the latest state.

### CODE REVIEW

File: sample/src/androidTest/kotlin/com/agoda/sample/TestActivityTest.kt [hunk 1]
```diff
@@ -67,7 +67,7 @@ class TestActivityTest {
                 action {
                     hasText("DISMISS")
                     click()
-                    idle(500)
+                    this@screen.idle(500)
```
Comment (cdsap) [inline sample/src/androidTest/kotlin/com/agoda/sample/TestActivityTest.kt]: why this change?

Comment (Unlimity) [reply sample/src/androidTest/kotlin/com/agoda/sample/TestActivityTest.kt]: After correct implementation of `DslMarker`, `idle` function is outside of the scope so you need to explicitly access screen to idle. Maybe we can think of something to make this function publicly accessible across all dsl? Maybe put it to `Screen`'s companion object?

Comment (Unlimity) [reply sample/src/androidTest/kotlin/com/agoda/sample/TestActivityTest.kt]: Moved `idle` to `Screen`'s companion object.
